services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seanard-graphql-book_library
    ports:
      - "${DOCKER_EXPOSED_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
